const colleges=[
    {
        id:1,
        ranking:39,
        image:"https://www.sangenbd.com/images/university-of-melbourne-overview.jpg",
        name:"THE UNIVERSITY OF MELBOURNE",
        level:"Bachelors",
        location:"Melbourne Australia",
        entry: "IELTS 6.5",
        cost: "AUD47672",
        INR:"INR 2583428.169",
        degree:"Bachelor of Commerce",
        country:"Australia",
    },
    {
        id:2,
        ranking:83,
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTY1FgMgzx0ml_NvnBUupj0XOPpb8Bm_-DjM5iv3Z-PjS-NFelsen80XDxVjuRf5xPA-rc&usqp=CAU",
        name:"THE UNIVERSITY OF NEW SOUTH WALES",
        level:"Masters",
        location:"Sydney, Australia",
        entry: "IELTS 6.5",
        cost: "AUD47680",
        INR:"INR 2583861.703",
        degree:"Master of Information Technology - Internetworking",
        country:"Australia",
    },
    {
        id:3,
        ranking:"",
        name:"THE AUSTRALIAN NATIONAL UNIVERSITY",
        image:"https://smapse.com/storage/2018/11/alphagamma-anu-summer-research-program-2017-opportunities.jpg",
        level:"Masters",
        location:"Bruce, Australia",
        entry: "IELTS 6.5",
        cost: "AUD50760",
        INR:"INR 2750772.232",
        degree:"Master of Computing - Artificial Intelligence",
        country:"Australia",

    },
    {
        id:1,
        ranking:"251",
        name:"RMIT UNIVERSITY",
        image:"https://www.rmit.edu.au/content/dam/rmit/rmit-images/marketing-only/about-sub-mastheads/City-Campus-Masthead-1920x960.jpg",
        level:"Bachelors",
        location:"Melbourne, Australia",
        entry: "IELTS 6.5",
        cost: "AUD40320",
        INR:"INR 2185010.567",
        degree:"Bachelor of Computer Science-Professional",
        country:"Australia",
    },
    {
        id:1,
        ranking:201,
        name:"QUEENSLAND UNIVERSITY OF TECHNOLOGY",
        image:"https://images.shiksha.com/mediadata/images/1575364977phpKtd6VW.jpeg",
        level:"Dual",
        location:"Brisbane, Australia",
        entry: "IELTS 6.5",
        cost: "AUD36700 ",
        INR:"INR 1988836.504",
        degree:"Bachelor of Business/Bachelor of Design (Interaction Design)",
        country:"Australia",
    },
    {
        id:1,
        ranking:251,
        name:"LA TROBE UNIVERSITY",
        image:"https://wtpindia.in/wp-content/uploads/2015/06/sylvia.jpg",
        level:"Bachelors",
        location:"West Wodonga, Australia",
        entry: " IELTS 6.0",
        cost: "AUD39000",
        INR:"INR 2113477.483",
        degree:"Bachelor of Biological Sciences-Genetics",
        country:"Australia",
    }
    ,
    {
        id:1,
        name:"THE UNIVERSITY OF NEW SOUTH WALES",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTY1FgMgzx0ml_NvnBUupj0XOPpb8Bm_-DjM5iv3Z-PjS-NFelsen80XDxVjuRf5xPA-rc&usqp=CAU",
        level:"Masters",
        location:"Sydney, Australia",
        entry: "IELTS 6.5",
        cost: "AUD47680",
        INR:"INR 2583861.703",
        degree:"Master of Information Technology - Internetworking",
        country:"Australia",
    },
    {
        id:1,
        ranking:83,
        name:"THE UNIVERSITY OF NEW SOUTH WALES",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTY1FgMgzx0ml_NvnBUupj0XOPpb8Bm_-DjM5iv3Z-PjS-NFelsen80XDxVjuRf5xPA-rc&usqp=CAU",
        level:"Masters",
        location:"Sydney, Australia",
        entry: "IELTS 6.5",
        cost: "AUD52320",
        INR:"INR 2835311.331",
        degree:"Master of Science (Research) in Physiology and Pharmacology",
        country:"Australia",
    },
    {
        id:1,
        ranking:251,
        name:"RMIT UNIVERSITY",
        image:"https://www.rmit.edu.au/content/dam/rmit/rmit-images/marketing-only/about-sub-mastheads/City-Campus-Masthead-1920x960.jpg",
        level:"Bachelors",
        location:"Sydney, Australia",
        entry: "IELTS 6.5",
        cost: "AUD45760",
        INR:"INR 2479813.58",
        degree:"Bachelor of Design(Communication Design)",
        country:"Australia",
    },
    {
        id:1,
        ranking:77,
        name:"THE UNIVERSITY OF QUEENSLAND",
        image:"https://images.shiksha.com/mediadata/images/1575364977phpKtd6VW.jpeg",
        level:"Bachelors",
        location:"BRISBANE, Australia",
        entry: "IELTS 6.5",
        cost: "AUD48160",
        INR:"2609873.733",
        degree:"Bachelor of Commerce-Applied Finance",
        country:"Australia",
    }
    ,{
        id:1,
        ranking:83,
        name:"THE UNIVERSITY OF NEW SOUTH WALES",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTY1FgMgzx0ml_NvnBUupj0XOPpb8Bm_-DjM5iv3Z-PjS-NFelsen80XDxVjuRf5xPA-rc&usqp=CAU",
        level:"Bachelors",
        location:"Sydney, Australia",
        entry: "IELTS 6.5",
        cost: "AUD47615",
        INR:"INR 2058303.177",
        degree:"Bachelor of Science - Genetics",
        country:"Australia",
    },
    {
        id:1,
        ranking:58,
        name:"MONASH UNIVERSITY",
        image:"https://www.monash.edu/__data/assets/image/0004/959530/clayton-campus-new-horizons-building-exterior-at-night-2013.jpg",
        level:"Bachelors",
        location:"Melbourne, Australia",
        entry: "IELTS 6.5",
        cost: "AUD39000",
        INR:"INR 2113477.483",
        degree:"Bachelor of Arts",
        country:"Australia",
    },
    {
        id:1,
        ranking:77,
        name:"THE UNIVERSITY OF QUEENSLAND",
        image:"https://images.shiksha.com/mediadata/images/1575364977phpKtd6VW.jpeg",
        level:"Doctorate",
        location:"Brisbane, Australia",
        entry: "IELTS 7.0",
        cost: "AUD91819 ",
        INR:"INR 4975830.488",
        degree:"Doctor of Medicine",
        country:"Australia",
    },
    {
        id:1,
        ranking:251,
        name:"RMIT UNIVERSITY",
        image:"https://www.rmit.edu.au/content/dam/rmit/rmit-images/marketing-only/about-sub-mastheads/City-Campus-Masthead-1920x960.jpg",
        level:"Doctorate",
        location:"Melbourne, Australia",
        entry: "IELTS 6.5",
        cost: "AUD36480",
        INR:"INR 2113477.483",
        degree:"PhD (Digital Health)",
        country:"Australia",
    },
    {
        "id": 1,
        "ranking": 251,
        "name": "Algonquin College",
        "image": "https://s7494.pcdn.co/public-relations/files/2013/02/front-view-2012-small2.jpg",
        "level": "Bachelors",
        "location": "Ottawa, Canada",
        "entry": "IELTS 6.0",
        "cost": "CAD 17,931",
        "INR": "INR 1,097,032",
        "degree": "Ontario College Diploma in Computer Programming",
        "country": "Canada"
    },
    {
        "id": 2,
        "ranking": 201,
        "name": "University of Toronto",
        "image": "https://images.shiksha.com/mediadata/images/1533275386phpeOjM3L.jpeg",
        "level": "Masters",
        "location": "Toronto, Canada",
        "entry": "IELTS 6.5",
        "cost": "CAD 30,000",
        "INR": "INR 1,836,000",
        "degree": "Master of Science in Computer Science",
        "country": "Canada"
    },
    {
        "id": 3,
        "ranking": 220,
        "name": "McGill University",
        "image": "https://reporter.mcgill.ca/wp-content/uploads/2024/05/McGill-Arts-2024-spring-crop-scaled.jpeg",
        "level": "Doctorate",
        "location": "Montreal, Canada",
        "entry": "IELTS 7.0",
        "cost": "CAD 18,000",
        "INR": "INR 1,102,800",
        "degree": "Ph.D. in Artificial Intelligence",
        "country": "Canada"
    },
    {
        "id": 4,
        "ranking": 310,
        "name": "University of British Columbia",
        "image": "https://images.shiksha.com/mediadata/images/1533551493phpKPRXCq.jpeg",
        "level": "Bachelors",
        "location": "Vancouver, Canada",
        "entry": "IELTS 6.5",
        "cost": "CAD 22,000",
        "INR": "INR 1,347,600",
        "degree": "Bachelor of Computer Science",
        "country": "Canada"
    },
    {
        "id": 5,
        "ranking": 290,
        "name": "University of Alberta",
        "image": "https://fosterstudy.com/wp-content/uploads/2022/05/study-in-university-of-alberta.jpg",
        "level": "Masters",
        "location": "Edmonton, Canada",
        "entry": "IELTS 6.5",
        "cost": "CAD 20,000",
        "INR": "INR 1,226,000",
        "degree": "Master of Data Science",
        "country": "Canada"
    },
    {
        "id": 6,
        "ranking": 325,
        "name": "York University",
        "image": "https://www.yorku.ca/housing/wp-content/uploads/sites/57/2021/01/Pond1-1024x680.jpg",
        "level": "Bachelors",
        "location": "Toronto, Canada",
        "entry": "IELTS 6.0",
        "cost": "CAD 21,000",
        "INR": "INR 1,287,300",
        "degree": "Bachelor of Cybersecurity",
        "country": "Canada"
    },
    {
        "id": 7,
        "ranking": 198,
        "name": "University of Waterloo",
        "image": "https://collegekampus.com/wp-content/uploads/2020/02/University-of-Waterloo01.jpeg",
        "level": "Doctorate",
        "location": "Waterloo, Canada",
        "entry": "IELTS 7.0",
        "cost": "CAD 19,500",
        "INR": "INR 1,194,700",
        "degree": "Ph.D. in Software Engineering",
        "country": "Canada"
    },
    {
        "id": 8,
        "ranking": 290,
        "name": "University of Calgary",
        "image": "https://www.highereducationdigest.com/wp-content/uploads/2023/05/1-1-550x330.jpg",
        "level": "Dual",
        "location": "Calgary, Canada",
        "entry": "IELTS 6.5",
        "cost": "CAD 24,000",
        "INR": "INR 1,464,000",
        "degree": "Dual Degree in IT & Business Analytics",
        "country": "Canada"
    },
    {
        "id": 9,
        "ranking": 370,
        "name": "Dalhousie University",
        "image": "https://www.dal.ca/_jcr_content/root/maincontent/main/container_274129951_/image.coreimg.jpeg/1730469126417/henry-hicks-building.jpeg",
        "level": "Masters",
        "location": "Halifax, Canada",
        "entry": "IELTS 6.5",
        "cost": "CAD 21,500",
        "INR": "INR 1,318,900",
        "degree": "Master of Information Technology",
        "country": "Canada"
    },
    {
        "id": 10,
        "ranking": 250,
        "name": "Simon Fraser University",
        "image": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0a/35/39/23/this-should-look-familiar.jpg?w=1200&h=-1&s=1",
        "level": "Bachelors",
        "location": "Burnaby, Canada",
        "entry": "IELTS 6.0",
        "cost": "CAD 19,000",
        "INR": "INR 1,162,700",
        "degree": "Bachelor of Artificial Intelligence",
        "country": "Canada"
    },
    {
        "id": 11,
        "ranking": 415,
        "name": "University of Manitoba",
        "image": "https://cdn.britannica.com/90/153890-050-32CB447A/Administration-Building-University-of-Manitoba-Winnipeg-Canada.jpg",
        "level": "Doctorate",
        "location": "Winnipeg, Canada",
        "entry": "IELTS 6.5",
        "cost": "CAD 17,500",
        "INR": "INR 1,071,400",
        "degree": "Ph.D. in Robotics",
        "country": "Canada"
    },
    {
        "id": 12,
        "ranking": 375,
        "name": "Carleton University",
        "image": "https://assets.collegedunia.com/public/college_data/images/studyabroad/appImage/college_2_17-11:26_carlton-university.jpeg",
        "level": "Masters",
        "location": "Ottawa, Canada",
        "entry": "IELTS 6.5",
        "cost": "CAD 20,500",
        "INR": "INR 1,257,300",
        "degree": "Master of AI and Machine Learning",
        "country": "Canada"
    },
    {
        "id": 13,
        "ranking": 450,
        "name": "University of Saskatchewan",
        "image": "https://cuebc.org/wp-content/uploads/2020/09/cover-University-of-Saskatchewan.jpg",
        "level": "Bachelors",
        "location": "Saskatoon, Canada",
        "entry": "IELTS 6.0",
        "cost": "CAD 18,500",
        "INR": "INR 1,131,200",
        "degree": "Bachelor of Software Engineering",
        "country": "Canada"
    },
    {
        "id": 14,
        "ranking": 490,
        "name": "Western University",
        "image": "https://cms.macleans.ca/wp-content/uploads/2024/08/Western-University-191030_UC_Tower_Fall_Sunset_UC-Tower-Fall-2019-1-2-scaled.jpg",
        "level": "Masters",
        "location": "London, Canada",
        "entry": "IELTS 6.5",
        "cost": "CAD 22,500",
        "INR": "INR 1,376,000",
        "degree": "Master of Data Science",
        "country": "Canada"
    },
    {
        "id": 15,
        "ranking": 350,
        "name": "Queen's University",
        "image": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/da/58/14/queens-university.jpg?w=900&h=500&s=1",
        "level": "Dual",
        "location": "Kingston, Canada",
        "entry": "IELTS 6.5",
        "cost": "CAD 23,500",
        "INR": "INR 1,435,000",
        "degree": "Dual Degree in Business & Computer Science",
        "country": "Canada"
    },
    {
        "id": 16,
        "ranking": 120,
        "name": "Harvard Medical School",
        "image": "https://meded.hms.harvard.edu/sites/hwpi.harvard.edu/files/styles/os_files_xxlarge/public/hms-med-ed/files/2gordon_hall.jpg?m=1692111162&itok=ldieXKfu",
        "level": "Doctorate",
        "location": "Boston, USA",
        "entry": "MCAT + IELTS 7.0",
        "cost": "USD 65,000",
        "INR": "INR 5,400,000",
        "degree": "Doctor of Medicine",
        "country": "USA"
    },
    {
        "id": 17,
        "ranking": 95,
        "name": "London School of Economics",
        "image": "https://upload.wikimedia.org/wikipedia/commons/f/f7/The_Land_Registry_Offices%2C_Lincoln_Inn_Fields.jpg",
        "level": "Masters",
        "location": "London, UK",
        "entry": "IELTS 7.0",
        "cost": "GBP 30,000",
        "INR": "INR 3,100,000",
        "degree": "MSc Finance",
        "country": "UK"
    },
    {
        "id": 18,
        "ranking": 180,
        "name": "University of Sydney",
        "image": "https://images.shiksha.com/mediadata/images/1515481785phphzFAcA.png",
        "level": "Bachelors",
        "location": "Sydney, Australia",
        "entry": "IELTS 6.5",
        "cost": "AUD 40,000",
        "INR": "INR 2,200,000",
        "degree": "Bachelor of Agriculture",
        "country": "Australia"
    },
    {
        "id": 19,
        "ranking": 210,
        "name": "Yale School of Art",
        "image": "https://artgallery.yale.edu/sites/default/files/styles/max_800x800/public/2023-03/2023-Kahn-ag-doc-412-0025-pub.jpg?itok=PeSs9Ro5",
        "level": "Masters",
        "location": "New Haven, USA",
        "entry": "Portfolio + IELTS 6.5",
        "cost": "USD 50,000",
        "INR": "INR 4,100,000",
        "degree": "Master of Fine Arts",
        "country": "USA"
    },
    {
        "id": 20,
        "ranking": 275,
        "name": "University of Guelph",
        "image": "https://grantme.com/wp-content/uploads/2022/05/OATKVOZUV5HLJNRY4W7OAXWKSM-scaled.jpg",
        "level": "Bachelors",
        "location": "Guelph, Canada",
        "entry": "IELTS 6.5",
        "cost": "CAD 25,000",
        "INR": "INR 1,525,000",
        "degree": "Bachelor of Agricultural Science",
        "country": "Canada"
    },    {
        id: 1,
        ranking: 5,
        image: "https://www.universityliving.com/blog/wp-content/uploads/2023/07/Banner-Image-The-University-of-Cambridge-1000x418.webp",
        name: "UNIVERSITY OF CAMBRIDGE",
        level: "Bachelors",
        location: "Cambridge, UK",
        entry: "IELTS 7.0",
        cost: "GBP 22,000",
        INR: "INR 2,420,000",
        degree: "Bachelor of Computer Science",
        country: "UK",
    },
    {
        id: 2,
        ranking: 8,
        image: "https://www.ox.ac.uk/sites/files/oxford/styles/ow_large_feature/s3/field/field_image_main/GAF-MPLS-PAD.jpg?itok=alpYzVAj",
        name: "UNIVERSITY OF OXFORD",
        level: "Masters",
        location: "Oxford, UK",
        entry: "IELTS 7.5",
        cost: "GBP 30,000",
        INR: "INR 3,300,000",
        degree: "Master of Data Science",
        country: "UK",
    },
    {
        id: 3,
        ranking: 15,
        image: "https://images.shiksha.com/mediadata/images/1678969832php9e6wQM_g.jpg",
        name: "IMPERIAL COLLEGE LONDON",
        level: "Doctorate",
        location: "London, UK",
        entry: "IELTS 7.0",
        cost: "GBP 35,000",
        INR: "INR 3,850,000",
        degree: "PhD in Artificial Intelligence",
        country: "UK",
    },
    {
        id: 4,
        ranking: 25,
        image: "https://cdn.britannica.com/97/126697-050-55D7CB5B/University-of-Edinburgh-St-Leonards-Hall-Scot.jpg",
        name: "UNIVERSITY OF EDINBURGH",
        level: "Bachelors",
        location: "Edinburgh, UK",
        entry: "IELTS 6.5",
        cost: "GBP 18,000",
        INR: "INR 1,980,000",
        degree: "Bachelor of Business Management",
        country: "UK",
    },
    {
        id: 5,
        ranking: 35,
        image: "https://images.shiksha.com/mediadata/images/1533553333phpfZ3OBo_g.jpg",
        name: "UNIVERSITY OF MANCHESTER",
        level: "Masters",
        location: "Manchester, UK",
        entry: "IELTS 6.5",
        cost: "GBP 23,000",
        INR: "INR 2,530,000",
        degree: "Master of Information Technology",
        country: "UK",
    },
    {
        id: 6,
        ranking: 40,
        image: "https://mastergradschools.com/wp-content/uploads/2024/08/LSE.jpg",
        name: "LONDON SCHOOL OF ECONOMICS",
        level: "Bachelors",
        location: "London, UK",
        entry: "IELTS 7.0",
        cost: "GBP 28,000",
        INR: "INR 3,080,000",
        degree: "Bachelor of Economics",
        country: "UK",
    },
    {
        id: 7,
        ranking: 50,
        image: "https://oidigitalinstitute.com/wp-content/uploads/2023/04/AdobeStock_498150538-University-of-Bristol-2-scaled.jpeg",
        name: "UNIVERSITY OF BRISTOL",
        level: "Masters",
        location: "Bristol, UK",
        entry: "IELTS 7.0",
        cost: "GBP 24,000",
        INR: "INR 2,640,000",
        degree: "Master of Computer Science",
        country: "UK",
    },
    {
        id: 8,
        ranking: 60,
        image: "https://ucarecdn.com/aea3b081-8984-467b-98c1-8d3104588a34/",
        name: "UNIVERSITY OF WARWICK",
        level: "Bachelors",
        location: "Warwick, UK",
        entry: "IELTS 6.5",
        cost: "GBP 19,000",
        INR: "INR 2,090,000",
        degree: "Bachelor of Engineering",
        country: "UK",
    },
    {
        id: 9,
        ranking: 65,
        image: "https://brive.com/media/images/brive-university-of-leeds-top-banner.jpg",
        name: "UNIVERSITY OF LEEDS",
        level: "Doctorate",
        location: "Leeds, UK",
        entry: "IELTS 6.5",
        cost: "GBP 27,000",
        INR: "INR 2,970,000",
        degree: "PhD in Machine Learning",
        country: "UK",
    },
    {
        id: 10,
        ranking: 70,
        image: "https://techportal.in/wp-content/uploads/2023/11/sheffield.jpg",
        name: "UNIVERSITY OF SHEFFIELD",
        level: "Masters",
        location: "Sheffield, UK",
        entry: "IELTS 6.5",
        cost: "GBP 21,000",
        INR: "INR 2,310,000",
        degree: "Master of Software Engineering",
        country: "UK",
    },
    {
        id: 11,
        ranking: 72,
        image: "https://www.surrey.ac.uk/sites/default/files/styles/focal_point_2000x1500/public/2024-05/Civil%20and%20Environmental%20Engineering%20PhD.jpg?h=38a4752e&itok=0VPxNoiu",
        name: "UNIVERSITY OF SURREY",
        level: "Bachelors",
        location: "Guildford, UK",
        entry: "IELTS 6.0",
        cost: "GBP 18,500",
        INR: "INR 2,035,000",
        degree: "Bachelor of Digital Technologies",
        country: "UK",
    },
    {
        id: 12,
        ranking: 80,
        image: "https://ucarecdn.com/fb92ffc9-f6d3-49dc-811d-bb4ec1c9315c/-/crop/800x450/0,42/-/preview/-/format/auto/",
        name: "UNIVERSITY OF WOLVERHAMPTON",
        level: "Masters",
        location: "Wolverhampton, UK",
        entry: "IELTS 6.0",
        cost: "GBP 20,000",
        INR: "INR 2,200,000",
        degree: "Master of Cyber Security",
        country: "UK",
    },
    {
        id: 13,
        ranking: 85,
        image: "https://uniacco.com/blog/wp-content/uploads/2020/05/University-of-Nottingham.jpg",
        name: "UNIVERSITY OF NOTTINGHAM",
        level: "Doctorate",
        location: "Nottingham, UK",
        entry: "IELTS 7.0",
        cost: "GBP 26,000",
        INR: "INR 2,860,000",
        degree: "PhD in Computer Science",
        country: "UK",
    },
    {
        id: 14,
        ranking: 90,
        image: "vhttps://images.indianexpress.com/2024/09/Southampton-University.jpg",
        name: "UNIVERSITY OF SOUTHAMPTON",
        level: "Masters",
        location: "Southampton, UK",
        entry: "IELTS 6.5",
        cost: "GBP 24,500",
        INR: "INR 2,695,000",
        degree: "Master of Artificial Intelligence",
        country: "UK",
    },
    {
        id: 9,
        ranking: 55,
        image: "https://oidigitalinstitute.com/wp-content/uploads/2023/04/AdobeStock_498150538-University-of-Bristol-2-scaled.jpeg",
        name: "UNIVERSITY OF BRISTOL",
        level: "Bachelors",
        location: "Bristol, UK",
        entry: "IELTS 6.5",
        cost: "GBP 20,500",
        INR: "INR 2,260,000",
        degree: "Bachelor of Pharmacy",
        country: "UK",
    },
    {
        id: 10,
        ranking: 65,
        image: "https://ucarecdn.com/fd9f03c0-2c0e-4673-9d0d-1236878bf24c/-/crop/800x450/0,42/-/preview/-/format/auto/",
        name: "UNIVERSITY OF MANCHESTER",
        level: "Masters",
        location: "Manchester, UK",
        entry: "IELTS 6.5",
        cost: "GBP 23,000",
        INR: "INR 2,530,000",
        degree: "Master of Finance",
        country: "UK",
    },
    {
        id: 11,
        ranking: 70,
        image: "https://images.shiksha.com/mediadata/images/1398677512phpKUT2VW.jpeg",
        name: "UNIVERSITY OF LIVERPOOL",
        level: "Bachelors",
        location: "Liverpool, UK",
        entry: "IELTS 6.5",
        cost: "GBP 21,000",
        INR: "INR 2,310,000",
        degree: "Bachelor of Marketing",
        country: "UK",
    },
    {
        id: 12,
        ranking: 75,
        image: "https://static.toiimg.com/thumb/48790292.cms?resizemode=75&width=1200&height=900",
        name: "UNIVERSITY OF LEEDS",
        level: "Masters",
        location: "Leeds, UK",
        entry: "IELTS 7.0",
        cost: "GBP 25,000",
        INR: "INR 2,750,000",
        degree: "Master of Marketing",
        country: "UK",
    },
    {
        id: 13,
        ranking: 80,
        image: "https://www.financialexpress.com/wp-content/uploads/2023/11/University-of-Sheffield-1.jpg",
        name: "UNIVERSITY OF SHEFFIELD",
        level: "Bachelors",
        location: "Sheffield, UK",
        entry: "IELTS 6.5",
        cost: "GBP 19,500",
        INR: "INR 2,145,000",
        degree: "Bachelor of Pharmacy",
        country: "UK",
    },{
        id: 1,
        ranking: 10,
        image: "https://thecollegepost.com/wp-content/uploads/2021/10/Harvard-University.jpg",
        name: "HARVARD UNIVERSITY",
        level: "Masters",
        location: "Cambridge, MA, USA",
        entry: "TOEFL 100",
        cost: "USD 50,000",
        INR: "INR 37,000,000",
        degree: "Master of Finance",
        country: "USA",
    },
    {
        id: 2,
        ranking: 12,
        image: "https://www.tclf.org/sites/default/files/styles/crop_2000x700/public/thumbnails/image/CA_Stanford_StanfordUniversity_courtesyWikimediaCommons_2011_005_Hero.jpg?itok=B8YAapxD",
        name: "STANFORD UNIVERSITY",
        level: "Bachelors",
        location: "Stanford, CA, USA",
        entry: "TOEFL 100",
        cost: "USD 53,000",
        INR: "INR 39,500,000",
        degree: "Bachelor of Marketing",
        country: "USA",
    },
    {
        id: 3,
        ranking: 5,
        image: "https://cdn.britannica.com/39/160139-050-147B020E/Eckhart-Hall-campus-Ryerson-Physical-Laboratory-University.jpg",
        name: "UNIVERSITY OF CHICAGO",
        level: "Masters",
        location: "Chicago, IL, USA",
        entry: "TOEFL 105",
        cost: "USD 60,000",
        INR: "INR 44,500,000",
        degree: "Master of Finance",
        country: "USA",
    },
    {
        id: 4,
        ranking: 15,
        image: "https://media-cldnry.s-nbcnews.com/image/upload/t_nbcnews-fp-1024-512,f_auto,q_auto:best/rockcms/2025-03/250307-columbia-university-lm-1255-48df8c.jpg",
        name: "COLUMBIA UNIVERSITY",
        level: "Bachelors",
        location: "New York City, NY, USA",
        entry: "TOEFL 100",
        cost: "USD 55,000",
        INR: "INR 40,750,000",
        degree: "Bachelor of Marketing",
        country: "USA",
    },
    {
        id: 5,
        ranking: 20,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjhVS1lVvblLmQjYHMl5EzsQyQFfmy-Umfdw&s",
        name: "YALE UNIVERSITY",
        level: "Masters",
        location: "New Haven, CT, USA",
        entry: "TOEFL 105",
        cost: "USD 57,000",
        INR: "INR 42,100,000",
        degree: "Master of Finance",
        country: "USA",
    },
    {
        id: 6,
        ranking: 22,
        image: "https://images.shiksha.com/mediadata/images/1533556731php9oeJON_g.png",
        name: "PRINCETON UNIVERSITY",
        level: "Bachelors",
        location: "Princeton, NJ, USA",
        entry: "TOEFL 100",
        cost: "USD 50,000",
        INR: "INR 37,000,000",
        degree: "Bachelor of Marketing",
        country: "USA",
    },    {
        "id": 1,
        "ranking": 1,
        "image": "https://thecollegepost.com/wp-content/uploads/2021/10/Harvard-University.jpg",
        "name": "HARVARD UNIVERSITY",
        "level": "Masters",
        "location": "Cambridge, USA",
        "entry": "TOEFL 100",
        "cost": "USD 45,000",
        "INR": "INR 33,00,000",
        "degree": "Master of Science in Artificial Intelligence",
        "country": "USA"
    },
    {
        "id": 2,
        "ranking": 3,
        "image": "https://www.tclf.org/sites/default/files/styles/crop_2000x700/public/thumbnails/image/CA_Stanford_StanfordUniversity_courtesyWikimediaCommons_2011_005_Hero.jpg?itok=B8YAapxD",
        "name": "STANFORD UNIVERSITY",
        "level": "Doctorate",
        "location": "Stanford, USA",
        "entry": "TOEFL 100",
        "cost": "USD 50,000",
        "INR": "INR 37,00,000",
        "degree": "PhD in Genetics",
        "country": "USA"
    },
    {
        "id": 3,
        "ranking": 5,
        "image": "https://snoopy.archdaily.com/images/archdaily/media/images/6045/dda8/f91c/81a2/6d00/0357/slideshow/shutterstock_575832073.jpg?1615191432&format=webp&width=640&height=580",
        "name": "MASSACHUSETTS INSTITUTE OF TECHNOLOGY",
        "level": "Bachelors",
        "location": "Cambridge, USA",
        "entry": "TOEFL 105",
        "cost": "USD 47,000",
        "INR": "INR 34,70,000",
        "degree": "Bachelor of Computer Science",
        "country": "USA"
    },
    {
        "id": 4,
        "ranking": 10,
        "image": "https://media-cldnry.s-nbcnews.com/image/upload/t_nbcnews-fp-1024-512,f_auto,q_auto:best/rockcms/2025-03/250307-columbia-university-lm-1255-48df8c.jpg",
        "name": "COLUMBIA UNIVERSITY",
        "level": "Masters",
        "location": "New York, USA",
        "entry": "TOEFL 100",
        "cost": "USD 50,000",
        "INR": "INR 37,00,000",
        "degree": "Master of Science in Artificial Intelligence",
        "country": "USA"
    },
    {
        "id": 5,
        "ranking": 12,
        "image": "https://goat.celtgo.com/storage/uploads/universities_image/University%20of%20California,%20Berkeley665728afd8a6b.png",
        "name": "UNIVERSITY OF CALIFORNIA, BERKELEY",
        "level": "Doctorate",
        "location": "Berkeley, USA",
        "entry": "TOEFL 105",
        "cost": "USD 40,000",
        "INR": "INR 29,60,000",
        "degree": "PhD in Agricultural Sciences",
        "country": "USA"
    },
    {
        "id": 6,
        "ranking": 18,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWenEICRd4ULft0p_xx4JghEWUWB9hUPtsGQ&s",
        "name": "UNIVERSITY OF WASHINGTON",
        "level": "Masters",
        "location": "Seattle, USA",
        "entry": "TOEFL 100",
        "cost": "USD 38,000",
        "INR": "INR 28,00,000",
        "degree": "Master of Science in Digital Health",
        "country": "USA"
    },
    {
        "id": 7,
        "ranking": 20,
        "image": "https://images.shiksha.com/mediadata/images/1533556731php9oeJON_g.png",
        "name": "PRINCETON UNIVERSITY",
        "level": "Bachelors",
        "location": "Princeton, USA",
        "entry": "TOEFL 100",
        "cost": "USD 47,000",
        "INR": "INR 34,70,000",
        "degree": "Bachelor of Computer Science",
        "country": "USA"
    },
    {
        "id": 8,
        "ranking": 22,
        "image": "https://www.tclf.org/sites/default/files/styles/crop_2000x700/public/thumbnails/image/CA_Stanford_StanfordUniversity_courtesyWikimediaCommons_2011_005_Hero.jpg?itok=B8YAapxD",
        "name": "STANFORD UNIVERSITY",
        "level": "Masters",
        "location": "Stanford, USA",
        "entry": "TOEFL 100",
        "cost": "USD 50,000",
        "INR": "INR 37,00,000",
        "degree": "MSc in Art and Craft Design",
        "country": "USA"
    },
    {
        "id": 9,
        "ranking": 30,
        "image": "https://cdn.britannica.com/39/160139-050-147B020E/Eckhart-Hall-campus-Ryerson-Physical-Laboratory-University.jpg",
        "name": "UNIVERSITY OF CHICAGO",
        "level": "Doctorate",
        "location": "Chicago, USA",
        "entry": "TOEFL 100",
        "cost": "USD 50,000",
        "INR": "INR 37,00,000",
        "degree": "PhD in Genetics",
        "country": "USA"
    },
    {
        "id": 10,
        "ranking": 40,
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQc5TFF7qYc_STUdMVMiWWPqGUTtxiQZ9rhLQ&s",
        "name": "CALIFORNIA INSTITUTE OF TECHNOLOGY",
        "level": "Masters",
        "location": "Pasadena, USA",
        "entry": "TOEFL 100",
        "cost": "USD 55,000",
        "INR": "INR 40,70,000",
        "degree": "Master of Science in Digital Health",
        "country": "USA"
    },
    {
        "id": 11,
        "ranking": 45,
        "image": "https://images.shiksha.com/mediadata/images/1532951415phpyJx0mH_g.jpg",
        "name": "UNIVERSITY OF MICHIGAN",
        "level": "Bachelors",
        "location": "Ann Arbor, USA",
        "entry": "TOEFL 100",
        "cost": "USD 38,000",
        "INR": "INR 28,00,000",
        "degree": "Bachelor of Agricultural Sciences",
        "country": "USA"
    },
    {
        "id": 12,
        "ranking": 50,
        "image": "https://questbridge.imgix.net/content/uploads/partners/yale-university/CommonApp2560_1-Courtyard.jpg?auto=compress%2Cformat&crop=focalpoint&fit=crop&fp-x=0.5&fp-y=0.5&h=800&q=90&w=800&s=a730e80b3d8211950dde98db72618b73",
        "name": "YALE UNIVERSITY",
        "level": "Doctorate",
        "location": "New Haven, USA",
        "entry": "TOEFL 100",
        "cost": "USD 52,000",
        "INR": "INR 38,40,000",
        "degree": "MD (Doctor of Medicine - MBBS)",
        "country": "USA"
    },
    {
        "id": 13,
        "ranking": 60,
        "image": "https://yourdreamschool.fr/wp-content/uploads/2020/10/shutterstock_108798089.jpg",
        "name": "COLUMBIA UNIVERSITY",
        "level": "Masters",
        "location": "New York, USA",
        "entry": "TOEFL 100",
        "cost": "USD 48,000",
        "INR": "INR 35,40,000",
        "degree": "Master of Science in Genetics",
        "country": "USA"
    },
    {
        "id": 14,
        "ranking": 65,
        "image": "https://www.doingcollege.com/wp-content/uploads/2022/11/UC_LA-new-690x380-2.jpg",
        "name": "UNIVERSITY OF CALIFORNIA, LOS ANGELES (UCLA)",
        "level": "Bachelors",
        "location": "Los Angeles, USA",
        "entry": "TOEFL 100",
        "cost": "USD 43,000",
        "INR": "INR 31,70,000",
        "degree": "Bachelor of Agricultural Sciences",
        "country": "USA"
    },
    {
        "id": 15,
        "ranking": 70,
        "image": "https://goat.celtgo.com/storage/uploads/universities_image/University%20of%20California,%20Berkeley665728afd8a6b.png",
        "name": "UNIVERSITY OF CALIFORNIA, BERKELEY",
        "level": "Doctorate",
        "location": "Berkeley, USA",
        "entry": "TOEFL 100",
        "cost": "USD 55,000",
        "INR": "INR 40,70,000",
        "degree": "PhD in Artificial Intelligence",
        "country": "USA"
    },
    {
        "id": 16,
        "ranking": 25,
        "image": "https://www.upenn.edu/sites/default/files/styles/default/public/2020-11/p-100297-master-v1-075a-1600x800.jpg?itok=apAkEATX",
        "name": "UNIVERSITY OF PENNSYLVANIA",
        "level": "Dual",
        "location": "Philadelphia, USA",
        "entry": "TOEFL 100",
        "cost": "USD 55,000",
        "INR": "INR 40,70,000",
        "degree": "Bachelor of Computer Science + Master of Business Administration (MBA)",
        "country": "USA"
    }

]
module.exports=colleges